import type { ChatImageAttachment } from './chatAttachments';

// Web display types for the current UI state. They stay aligned with the
// runtime event/envelope concepts and can overlap with CLI shapes where useful,
// but they are not an exact mirror of `packages/cli/src/state/types.ts` because
// the web layer carries additional UI-only fields such as image attachments and
// pane metadata. The dispatch envelope / reference shapes mirror
// `docs/spaces.md` §5 (the 主从调度契约), so the UI renders exactly what the
// real engine will stream once P1 lands.

export type DisplayRole = 'user' | 'assistant' | 'system' | 'tool' | 'space' | 'dispatch';

export type ToolStatus = 'running' | 'done' | 'error';

export type ToolCallView = {
  toolCallId?: string;
  name: string;
  args: string;
  result: string;
  status: ToolStatus;
};

export type SpaceView = {
  /** The concrete dispatch pane id rendered by the UI. */
  id: string;
  /** The catalog space id, e.g. explore / terminal. */
  spaceId: string;
  label: string;
};

/**
 * A structured reference produced by a work conversation (`docs/spaces.md` §5.3).
 * `file` carries a path (+ optional line range), `url` a link, `artifact`/`memory`
 * an id. References are how a dispatch points back at concrete deliverables and
 * how the next dispatch inherits context.
 */
export type Reference = {
  kind: 'file' | 'url' | 'artifact' | 'memory';
  path?: string;
  lines?: string;
  url?: string;
  id?: string;
  mime?: string;
  title?: string;
  source?: 'generated' | 'explicit' | 'imported';
  /** Which work conversation produced it (溯源). */
  sourceConversationId?: string;
};

/**
 * The upward envelope a work conversation returns to `session` (`docs/spaces.md`
 * §5.2). `status` is binary; everything else (timeout, follow-up question,
 * partial result) is expressed in natural language via `summary` — no machine
 * enum, per the spec. `summary` is the one field always written back to the
 * session main thread as a breadcrumb.
 */
export type Envelope = {
  status: 'success' | 'failed';
  summary: string;
  /** Full deliverable: a diff, findings, or finished prose. */
  content?: string;
  references?: Reference[];
  meta?: { rounds?: number; ms?: number; tokens?: number };
};

/**
 * One dispatch round, surfaced inline in the conversation as the breadcrumb
 * (`docs/spaces.md` §6 / §8.1). `goal` is the sub-goal session handed down;
 * `envelope` is filled once the work conversation returns. `viaShortcut` marks
 * a `/space:` round (decided by the user, not the session LLM) — same contract.
 */
export type DispatchView = {
  space: string;
  label: string;
  goal: string;
  viaShortcut?: boolean;
  envelope?: Envelope;
};

export type DisplayMessage = {
  id: number;
  /** Durable session entry id, present for server-paginated history. */
  entryId?: string;
  role: DisplayRole;
  /** Present for user / assistant / system messages. */
  text?: string;
  /** Present for tool messages (kept for the console; not rendered inline). */
  tool?: ToolCallView;
  /** Present for space messages (a workspace breadcrumb). */
  space?: SpaceView;
  /** The result of THIS dispatch, frozen onto its own card once it returns — so
   *  each space card shows its own stats independently of the reused live pane
   *  (which a later dispatch to the same space resets). */
  envelope?: Envelope;
  /** Deliverables produced by this workspace dispatch, shown inline in chat. */
  artifacts?: ArtifactView[];
  /** Present for dispatch messages (a dispatch-round breadcrumb). */
  dispatch?: DispatchView;
  /** Present for user messages that include image previews. Full bytes are not stored here. */
  attachments?: ChatImageAttachment[];
  /** The concrete workspace pane this chip belongs to, so clicking opens that tab. */
  spaceId?: string;
  /** Wall-clock ms the message was committed (for the assistant card footer). */
  ts?: number;
};

/** A high-risk tool waiting on the user's y/n before it runs (HITL). */
export type ToolApprovalRequest = {
  approvalId: string;
  name: string;
  args: string;
  /** Multi-line preview of the concrete change/command (first line is a header). */
  preview?: string;
  status?: 'waiting' | 'approved' | 'rejected' | 'timeout' | 'expired' | 'retry';
  message?: string;
};

export type RunStatus = 'idle' | 'running';

/**
 * An artifact surfaced in a workspace pane. Derived from the dispatch envelope's
 * `references` (the real, contract-driven source, `docs/spaces.md` §5.2), with a
 * heuristic fallback from file-mutating tool results for the legacy SSE path
 * that doesn't emit envelopes yet (see `useWorkbench`).
 */
export type ArtifactView = {
  id: number;
  spaceId: string;
  kind: Reference['kind'] | 'diff';
  title: string;
  detail: string;
  /** For local files generated by workspace tools. */
  path?: string;
  /** Tool-produced body to preview inline, e.g. a write/edit diff. */
  preview?: string;
  /** For `url` references — opens in a new tab. */
  href?: string;
  /** For `file` references — the line range, shown as a badge. */
  lines?: string;
};

export type WorkContext = {
  source: string;
  detail: string;
};

/**
 * One prose message a work space emitted in the 调度台, positioned in the tool
 * stream by `after` (= how many tools preceded it), so the console interleaves
 * messages and tools in order. Lets the user read the sub-space's own output and
 * confirm the result was carried back to main (carry-back, docs/spaces.md §5.2).
 */
export type PaneMessage = {
  text: string;
  after: number;
};

export type WorkspaceTransitionView = {
  fromSpace: string;
  toSpace: string;
  status: 'handoff' | 'completed' | 'failed';
  message: string;
  createdAt: string;
};

/**
 * One workspace `session` dispatched into during a run, accumulated for the 调度台
 * (the WorkSpace console). Each `dispatch start` opens a pane (a tab); the tools
 * that run while it's active land in `tools` (committed in place on `end`), and
 * the work conversation's `envelope` (§5.2) is attached when it returns. The
 * master-slave tree is depth-1 (§5.4), so panes never nest.
 */
export type WorkPane = {
  /** Concrete pane id. The UI keeps one pane per `spaceId`. */
  id: string;
  /** Durable workspace session id, used by trace/debug views. */
  sessionId?: string;
  /** Catalog space id, e.g. explore / terminal. */
  spaceId: string;
  label: string;
  /** The dispatch sub-goal this pane is executing (§5.1 `goal`). */
  goal?: string;
  /** The distilled handoff this pane received from the session or previous pane. */
  context?: WorkContext;
  startedAt: number;
  endedAt?: number;
  budget?: {
    maxToolIterations: number;
    timeoutMs?: number;
  };
  tools: ToolCallView[];
  /** The work space's own prose, interleaved with `tools` by `after` (§5.2). */
  messages?: PaneMessage[];
  artifacts: ArtifactView[];
  /** Visible workspace switch evidence restored from durable session entries. */
  transitions?: WorkspaceTransitionView[];
  /** UI-only marker: artifacts before this index belong to prior entries into the same reused space. */
  currentRunArtifactStart?: number;
  /** The upward envelope once the work conversation returns (§5.2). */
  envelope?: Envelope;
  /** Latest low-sensitive progress checkpoint from runtime/provider lifecycle. */
  statusLine?: string;
  status: 'running' | 'done' | 'error';
};
